version: '3'

services:
  db:
    image: postgres:9.6
  
  gn-erp:
    build: .
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      DEBUG: "True"
      SECRET_KEY: secret
    command: start_dev
