# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0024_auto_20171212_1257'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_student', to='admission.Registration')),
            ],
        ),
    ]
